const mongoose = require('mongoose');

/* ── Actionable AI Insight (generated by InsightGenerator after each KPI calc) */
const insightSchema = new mongoose.Schema(
  {
    category:         { type: String },   // energy | water | waste | ghg | social | governance
    title:            { type: String },   // ≤10 words
    description:      { type: String },   // 1-2 sentences, cites actual metric values
    estimated_impact: { type: String },   // quantified improvement estimate
    formula_used:     { type: String },   // exact arithmetic expression backing the estimate
  },
  { _id: false }
);

const auditTrailEntrySchema = new mongoose.Schema(
  {
    action: { type: String, required: true },
    timestamp: { type: Date, default: Date.now },
    triggeredBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  },
  { _id: false }
);

const kpiResultSchema = new mongoose.Schema(
  {
    companyId: { type: mongoose.Schema.Types.ObjectId, ref: 'Company', required: true },
    financialYear: { type: String, required: true },
    reportStatus: { type: String, enum: ['in_progress', 'complete'], default: 'in_progress' },

    financialData: {
      revenue_inr_crore: Number,
      total_employees: Number,
      financial_year: String,
    },

    environmentalKpis: {
      // Existing — Scope 1 & 2
      scope1_tco2e: Number,
      scope2_tco2e: Number,
      ghg_intensity_ppp: Number,
      // Scope 3
      scope3_tco2e: Number,
      // Energy
      total_energy_kwh: Number,
      total_energy_gj: Number,
      renewable_energy_pct: Number,
      renewable_energy_gj: Number,
      energy_intensity_per_rupee: Number,
      // GHG intensity per rupee
      ghg_intensity_per_rupee: Number,
      // Water
      total_water_kl: Number,
      water_intensity: Number,
      water_recycled_pct: Number,
      water_intensity_per_rupee: Number,
      water_withdrawal_surface_kl: Number,
      water_withdrawal_ground_kl: Number,
      water_withdrawal_third_party_kl: Number,
      water_discharged_kl: Number,
      // Waste
      total_waste_mt: Number,
      waste_intensity: Number,
      waste_recovered_pct: Number,
      hazardous_waste_mt: Number,
      non_hazardous_waste_mt: Number,
      plastic_waste_mt: Number,
      ewaste_mt: Number,
      waste_recycled_mt: Number,
      waste_reused_mt: Number,
      waste_landfill_mt: Number,
      // Air emissions
      nox_mt: Number,
      sox_mt: Number,
      pm_mt: Number,
      // Additional air pollutants — BRSR Principle 6 Q5
      pop_mt: Number,
      voc_mt: Number,
      hap_mt: Number,
      // Additional waste types — BRSR Principle 6 Q8
      bio_medical_waste_mt: Number,
      construction_waste_mt: Number,
      battery_waste_mt: Number,
      radioactive_waste_mt: Number,
      waste_incinerated_mt: Number,
    },

    socialKpis: {
      // Existing
      wellbeing_spend_pct_revenue: Number,
      female_wage_pct: Number,
      small_town_wage_pct: Number,
      msme_procurement_pct: Number,
      posh_complaints_count: Number,
      // Safety / LTIFR
      ltifr_employees: Number,
      ltifr_workers: Number,
      fatalities_employees: Number,
      fatalities_workers: Number,
      total_recordable_injuries_employees: Number,
      // Workforce headcount
      permanent_employees_total: Number,
      permanent_employees_male: Number,
      permanent_employees_female: Number,
      contract_employees_total: Number,
      differently_abled_employees: Number,
      // Wages / parity
      median_wage_male_inr: Number,
      median_wage_female_inr: Number,
      median_wage_ratio: Number,
      // Training & turnover
      safety_training_pct: Number,
      turnover_rate_male: Number,
      turnover_rate_female: Number,
      // Board diversity
      women_in_board_pct: Number,
      // Workers (separate from employees — BRSR Q18)
      permanent_workers_total: Number,
      permanent_workers_male: Number,
      permanent_workers_female: Number,
      other_workers_total: Number,
      other_employees_total: Number,
      differently_abled_workers: Number,
      // Leadership & governance
      women_in_kmp_pct: Number,
      // Inclusive
      union_membership_pct: Number,
      human_rights_training_pct: Number,
      // Employee benefit coverage — BRSR Principle 3 EI 1
      health_insurance_employees_pct: Number,
      health_insurance_workers_pct: Number,
      accident_insurance_employees_pct: Number,
      accident_insurance_workers_pct: Number,
      maternity_benefits_pct: Number,
      paternity_benefits_pct: Number,
      daycare_facilities_pct: Number,
      pf_coverage_pct: Number,
      gratuity_coverage_pct: Number,
      esi_coverage_pct: Number,
    },

    governanceKpis: {
      // Existing
      data_breach_pct_incidents: Number,
      accounts_payable_days: Number,
      related_party_purchase_pct: Number,
      related_party_sales_pct: Number,
      // New regulatory
      regulatory_fines_count: Number,
      regulatory_fines_inr: Number,
      anti_competitive_cases: Number,
      conflict_of_interest_complaints: Number,
      // Consumer complaints — BRSR Principle 9 EI 3
      data_privacy_complaints: Number,
      advertising_complaints: Number,
      cyber_security_complaints: Number,
      essential_services_complaints: Number,
      restrictive_trade_complaints: Number,
      unfair_trade_complaints: Number,
      product_recall_voluntary: Number,
      product_recall_forced: Number,
    },

    /* AI-generated actionable insights — replaced per-category on each document verify */
    ai_insights: { type: [insightSchema], default: [] },

    generatedAt: { type: Date },
    auditTrail:  { type: [auditTrailEntrySchema], default: [] },
  },
  { timestamps: true }
);

module.exports = mongoose.model('KpiResult', kpiResultSchema);
