export const BRSR_QUALITATIVE_QUESTIONS = [
  // Section B — Policy mapping (9 NGRBC Principles)
  { id: 'sb_p1_policy', group: 'Section B — Policy Mapping', principle: 'P1',
    question: 'Does your entity\'s policy cover Principle 1 (Ethical, Transparent & Accountable conduct) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board? Provide web link if available.' },
  { id: 'sb_p2_policy', group: 'Section B — Policy Mapping', principle: 'P2',
    question: 'Does your entity\'s policy cover Principle 2 (Sustainable & Safe Goods/Services) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board? Provide web link.' },
  { id: 'sb_p3_policy', group: 'Section B — Policy Mapping', principle: 'P3',
    question: 'Does your entity\'s policy cover Principle 3 (Employee Well-being) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board? Provide web link.' },
  { id: 'sb_p4_policy', group: 'Section B — Policy Mapping', principle: 'P4',
    question: 'Does your entity\'s policy cover Principle 4 (Stakeholder Interests & Responsiveness) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board?' },
  { id: 'sb_p5_policy', group: 'Section B — Policy Mapping', principle: 'P5',
    question: 'Does your entity\'s policy cover Principle 5 (Human Rights) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board? Provide web link to Child Labour/Anti-Bribery policy.' },
  { id: 'sb_p6_policy', group: 'Section B — Policy Mapping', principle: 'P6',
    question: 'Does your entity\'s policy cover Principle 6 (Environmental Protection & Restoration) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board? Provide web link to ESG/Environmental policy.' },
  { id: 'sb_p7_policy', group: 'Section B — Policy Mapping', principle: 'P7',
    question: 'Does your entity\'s policy cover Principle 7 (Responsible Policy Advocacy) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board?' },
  { id: 'sb_p8_policy', group: 'Section B — Policy Mapping', principle: 'P8',
    question: 'Does your entity\'s policy cover Principle 8 (Inclusive Growth & Equitable Development) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board?' },
  { id: 'sb_p9_policy', group: 'Section B — Policy Mapping', principle: 'P9',
    question: 'Does your entity\'s policy cover Principle 9 (Responsible Consumer Engagement) and its core elements?',
    type: 'yes_no', followUp: 'If Yes — Has the policy been approved by the Board?' },
  // Section B — Governance
  { id: 'sb_esg_director', group: 'Section B — Governance', principle: 'Governance',
    question: 'Name and designation of the Director responsible for the Business Responsibility & Sustainability Report.',
    type: 'text' },
  { id: 'sb_esg_committee', group: 'Section B — Governance', principle: 'Governance',
    question: 'Is there a specified Board Committee responsible for sustainability/ESG decisions? If yes, provide name of committee and chairperson.',
    type: 'yes_no_text' },
  { id: 'sb_external_assessment', group: 'Section B — Governance', principle: 'Governance',
    question: 'Has the entity carried out independent external assessment/evaluation of its policies? If yes, provide name of agency.',
    type: 'yes_no_text' },
  // P2 — Sustainable Products
  { id: 'p2_pat_scheme', group: 'P2 — Sustainable Products', principle: 'P2',
    question: 'Does the entity have any sites/facilities identified as Designated Consumers (DCs) under the PAT (Perform, Achieve & Trade) Scheme?',
    type: 'yes_no_text' },
  { id: 'p2_epr_compliance', group: 'P2 — Sustainable Products', principle: 'P2',
    question: 'Is Extended Producer Responsibility (EPR) applicable to the entity\'s activities? If yes, is the waste collection plan in line with the EPR plan submitted to Pollution Control Boards?',
    type: 'yes_no_text' },
  { id: 'p2_sustainable_sourcing', group: 'P2 — Sustainable Products', principle: 'P2',
    question: 'Does the entity have procedures in place for sustainable sourcing? If yes, what percentage of inputs were sourced sustainably in FY 2024-25?',
    type: 'yes_no_text' },
  // P3 — Employee Well-being
  { id: 'p3_ohsms', group: 'P3 — Employee Well-being', principle: 'P3',
    question: 'Has an Occupational Health & Safety Management System (OHSMS) been implemented? If yes, describe coverage and scope.',
    type: 'yes_no_text' },
  { id: 'p3_equal_opportunity', group: 'P3 — Employee Well-being', principle: 'P3',
    question: 'Does the entity have an equal opportunity policy as per the Rights of Persons with Disabilities Act, 2016? If yes, provide web link.',
    type: 'yes_no_text' },
  { id: 'p3_grievance_mechanism', group: 'P3 — Employee Well-being', principle: 'P3',
    question: 'Describe the grievance redressal mechanism available for permanent employees, contract employees, permanent workers, and contract workers.',
    type: 'text' },
  // P4 — Stakeholders
  { id: 'p4_stakeholder_identification', group: 'P4 — Stakeholders', principle: 'P4',
    question: 'Describe the processes for identifying key stakeholder groups of the entity.',
    type: 'text' },
  { id: 'p4_stakeholder_engagement', group: 'P4 — Stakeholders', principle: 'P4',
    question: 'List the key stakeholder groups, channels of communication, and frequency of engagement (Annually/Half-yearly/Quarterly/Other).',
    type: 'text' },
  // P5 — Human Rights
  { id: 'p5_anti_corruption_policy', group: 'P5 — Human Rights', principle: 'P5',
    question: 'Does the entity have an anti-corruption or anti-bribery policy? If yes, provide brief details and web link.',
    type: 'yes_no_text' },
  { id: 'p5_hr_focal_point', group: 'P5 — Human Rights', principle: 'P5',
    question: 'Is there a focal point (Individual/Committee) responsible for addressing human rights impacts or issues caused by the business?',
    type: 'yes_no_text' },
  { id: 'p5_hr_grievance_mechanism', group: 'P5 — Human Rights', principle: 'P5',
    question: 'Describe the internal mechanisms in place to redress grievances related to human rights issues (discrimination, child labour, forced labour, wages).',
    type: 'text' },
  // P6 — Environment
  { id: 'p6_zero_liquid_discharge', group: 'P6 — Environment', principle: 'P6',
    question: 'Has the entity implemented a mechanism for Zero Liquid Discharge (ZLD)? If yes, provide coverage and implementation details.',
    type: 'yes_no_text' },
  { id: 'p6_ecologically_sensitive', group: 'P6 — Environment', principle: 'P6',
    question: 'Does the entity have operations/offices in ecologically sensitive areas (national parks, wildlife sanctuaries, biosphere reserves, wetlands, coastal zones)? If yes, list location, type of operation, and compliance status.',
    type: 'yes_no_text' },
  { id: 'p6_ghg_reduction_projects', group: 'P6 — Environment', principle: 'P6',
    question: 'Does the entity have any specific projects or initiatives related to reducing GHG emissions? If yes, provide details.',
    type: 'yes_no_text' },
  { id: 'p6_business_continuity', group: 'P6 — Environment', principle: 'P6',
    question: 'Does the entity have a Business Continuity and Disaster Management Plan? Provide a 100-word summary or web link.',
    type: 'text' },
  // P7 — Policy Advocacy
  { id: 'p7_trade_associations', group: 'P7 — Policy Advocacy', principle: 'P7',
    question: 'How many trade/industry chambers or associations is the entity affiliated with? List the top 10 (by total membership) and indicate whether each has national or state reach.',
    type: 'text' },
  // P8 — Inclusive Growth
  { id: 'p8_community_grievance', group: 'P8 — Inclusive Growth', principle: 'P8',
    question: 'Describe the mechanisms to receive and redress grievances of the community.',
    type: 'text' },
  // P9 — Consumer
  { id: 'p9_complaint_mechanism', group: 'P9 — Consumer', principle: 'P9',
    question: 'Describe the mechanisms in place to receive and respond to consumer complaints and feedback.',
    type: 'text' },
  { id: 'p9_cyber_security_policy', group: 'P9 — Consumer', principle: 'P9',
    question: 'Does the entity have a framework/policy on cyber security and data privacy risks? If yes, provide web link.',
    type: 'yes_no_text' },
];

export const QUESTION_GROUPS = [...new Set(BRSR_QUALITATIVE_QUESTIONS.map(q => q.group))];
